name: Provision EKS

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2  # Updated to v2 for the latest features
        with:
          terraform_version: 1.5.6  # Use the latest stable version or your required version

      - name: List files for debugging
        run: ls -l terraform  # Check if the directory and files are present

      - name: Initialize Terraform
        working-directory: terraform
        run: terraform init

      - name: Validate Terraform
        working-directory: terraform
        run: terraform validate

      - name: Apply Terraform
        working-directory: terraform
        run: terraform apply
