name: Provision EKS

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6  # Use the latest stable version or your required version

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::891377120087:role/github-action-role
          aws-region: us-east-1

      - name: List files for debugging
        run: ls -l terraform  # Check if the directory and files are present

      - name: Initialize Terraform
        working-directory: terraform
        run: terraform init

      - name: Select Terraform Workspace
        working-directory: terraform
        run: terraform workspace select ${WORKSPACE_NAME} || terraform workspace new ${WORKSPACE_NAME}
        env:
          WORKSPACE_NAME: default  # You can change this to the desired workspace name

      - name: Validate Terraform
        working-directory: terraform
        run: terraform validate

      - name: Plan Terraform
        working-directory: terraform
        run: terraform plan

      - name: Apply Terraform
        working-directory: terraform
        run: terraform apply -auto-approve
