name: Provision EKS

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Initialize Terraform
        run: terraform init terraform/

      - name: Validate Terraform
        run: terraform validate terraform/

      - name: Apply Terraform
        run: terraform apply -auto-approve terraform/
